stages:
  - build-test
  - publish
  - installer
  - integration-test
  - integration-test--execution--1
  - integration-test--execution--2
  - integration-test--execution--3
  - integration-test--execution--4
  - integration-test--execution--5
  - integration-test--execution--6
  - integration-test--execution--7
  - delivery 

before_script:
  - export CI_AUTO_TAGGING_IS_ENABLED="true"
  - export CI_AUTO_TAGGING_MESSAGE="GitLab CI continuous delivery auto tagging job"
  - export CI_AUTO_TAGGING_TAG_NAME="deliverable"
  - export CI_GIT_SERVER_URL="git.talsen.team"
  - export CI_GIT_SERVER_USER_GIT="git"
  - export CI_GIT_SERVER_SSH_PORT="30222"

build-test-dotnet-application:
  stage: 'build-test'
  tags:
    - 'dotnet-core'
    - 'build'
  except:
    refs:
      - deliverable
  script:    
    - /bin/bash bash-gitlab-ci/run-tests.sh
    - /bin/bash bash-gitlab-ci/run-sonarscanner.sh
    
publish-dotnet-application:
  stage: 'publish'
  tags:
    - 'dotnet-core'
    - 'build'
  artifacts:
    paths:
      -  'publish'
  except:
    refs:
      - deliverable
  script:
    - cd src/oppo-terminal
    - dotnet publish -c Release -o ../../publish

build-debian-installer:
  dependencies: 
    - 'publish-dotnet-application'
  artifacts:
    paths:
      -  'installer/oppo-terminal.deb'
  stage: 'installer'
  tags:
    - 'debian-installer'
  except:
    refs:
      - deliverable
  script:    
    - cd installer/oppo-terminal
    - chmod -R 0775 DEBIAN
    - mkdir -p usr/bin
    - cp ../../publish/* usr/bin
    - rm -f usr/bin/*.pdb
    - cd ..
    - dpkg --build oppo-terminal

prepare-integration-test:
  dependencies: 
    - 'build-debian-installer'
  stage: 'integration-test'
  tags:
    - 'dotnet-core'
    - 'integration-test'
  except:
    refs:
      - deliverable
  before_script:
    - /bin/bash bash-gitlab-ci/run-installer.sh
  script:
    - echo "Preparation done ..."

run-integration-test--hello:
  extends: prepare-integration-test
  stage: 'integration-test--execution--1'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-hello.sh

run-integration-test--new-sln--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--2'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-new-sln--success.sh -

run-integration-test--new-sln-verbose--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--3'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-new-sln--success.sh verbose

run-integration-test--new-opcuaapp--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--4'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-new-opcuaapp--success.sh -

run-integration-test--new-opcuaapp-verbose--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--5'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-new-opcuaapp--success.sh verbose

run-integration-test--build-opcuaapp--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--6'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-build-opcuaapp--success.sh -

run-integration-test--build-opcuaapp-verbose--success:
  extends: prepare-integration-test
  stage: 'integration-test--execution--7'
  script:
    - /bin/bash bash-gitlab-ci/integration-tests/run-build-opcuaapp--success.sh verbose

mark-repository-as-deliverable:
  stage: 'delivery'
  tags:
    - 'set-delivery-tag'
  except:
    refs:
      - deliverable
  script:
    - echo "Mark repository as deliverable..."
    - /bin/bash /utility/auto-tagging/run-auto-tagging.sh
