stages:
  - build-test
  - publish
  - installer
  - integration-test

build-and-test-dotnet-application:
  stage: 'build-test'
  tags:
    - 'dotnet-core'
    - 'build'
  script:    
    - /bin/bash bash-gitlab-ci/run-dotnet-tests.sh
    - /bin/bash bash-gitlab-ci/run-sonarscanner.sh
    
publish-dotnet-application:
  stage: 'publish'
  tags:
    - 'dotnet-core'
    - 'build'
  artifacts:
    paths:
      -  'publish'
  script:
    - /bin/bash bash-gitlab-ci/run-dotnet-publish.sh

debian-installer:
  dependencies: 
    - 'publish-dotnet-application'
  artifacts:
    paths:
      -  'installer/open62541--v0.3.0.deb'
      -  'installer/oppo-terminal.deb'
  stage: 'installer'
  tags:
    - 'debian-installer'
  script:
    - /bin/bash bash-gitlab-ci/run-dpkg-build--open62541--v0.3.0.sh
    - /bin/bash bash-gitlab-ci/run-dpkg-build--oppo-terminal.sh

run-integration-test:
  dependencies: 
    - 'debian-installer'
  stage: 'integration-test'
  tags:
    - 'dotnet-core'
    - 'integration-test'
  script:
    - /bin/bash bash-gitlab-ci/run-dpkg-install--open62541--v0.3.0.sh
    - /bin/bash bash-gitlab-ci/run-dpkg-install--oppo-terminal.sh
    - /bin/bash bash-gitlab-ci/run-integration-tests.sh
