stages:
  - build-test
  - publish
  - installer
  - integration-test
  - delivery 

before_script:
  - export CI_AUTO_TAGGING_IS_ENABLED="true"
  - export CI_AUTO_TAGGING_MESSAGE="GitLab CI continuous delivery auto tagging job"
  - export CI_AUTO_TAGGING_TAG_NAME="deliverable"
  - export CI_GIT_SERVER_URL="git.talsen.team"
  - export CI_GIT_SERVER_USER_GIT="git"
  - export CI_GIT_SERVER_SSH_PORT="30222"

build-test-dotnet-application:
  stage: 'build-test'
  tags:
    - 'dotnet-core'
    - 'build'
  except:
    refs:
      - deliverable
  script:    
    - dotnet test oppo-terminal.tests.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - /bin/bash bash-gitlab-ci/run-sonarscanner.sh
    
publish-dotnet-application:
  stage: 'publish'
  tags:
    - 'dotnet-core'
    - 'build'
  artifacts:
    paths:
      -  'publish'
  except:
    refs:
      - deliverable
  script:
    - cd oppo-terminal
    - dotnet publish -c Release -o ../publish

build-debian-installer:
  dependencies: 
    - 'publish-dotnet-application'
  artifacts:
    paths:
      -  'installer/oppo-terminal.deb'
  stage: 'installer'
  tags:
    - 'debian-installer'
  except:
    refs:
      - deliverable
  script:    
    - cd installer/oppo-terminal
    - chmod -R 0775 DEBIAN
    - mkdir -p usr/bin
    - cp ../../publish/* usr/bin
    - rm -f usr/bin/*.pdb
    - cd ..
    - dpkg --build oppo-terminal

run-integration-test:
  dependencies: 
    - 'build-debian-installer'
  stage: 'integration-test'
  tags:
    - 'dotnet-core'
    - 'integration-test'
  except:
    refs:
      - deliverable
  script:
    - dpkg-query -l
    - dotnet --version
    - cd installer
    - dpkg -i oppo-terminal.deb
    - dotnet /usr/bin/oppo-terminal.dll

mark-repository-as-deliverable:
  stage: 'delivery'
  tags:
    - 'set-delivery-tag'
  except:
    refs:
      - deliverable
  script:
    - echo "Mark repository as deliverable..."
    - /bin/bash /utility/auto-tagging/run-auto-tagging.sh
